### ISSUE TITLE
No write acces to /root/.config/calibre

### ISSUE THREAD

**Issue by ethanopp** [Thraxis/docker-lazylibrarian-calibre#2]
Calibredb is not post-processing books correctly because of a dir on the container side (not accessible to /config) that does not have write permissions.

LOG:
Timestamp | Level | Message
-- | -- | --
2017-07-22 15:43:33 | DEBUG | Restart processDir job in 10 minutes
2017-07-22 15:43:33 | DEBUG | Stop processDir job
2017-07-22 15:43:33 | INFO | 1 book/mag processed.
2017-07-22 15:43:33 | DEBUG | Snatched direct Amy Poehler - Yes Please LL.(20910157) is not in download directory
2017-07-22 15:43:33 | DEBUG | /downloads/Amy Poehler - Yes Please LL.(20910157) is not a directory?
2017-07-22 15:43:33 | INFO | Looking for eBook Amy Poehler - Yes Please LL.(20910157) in /downloads
2017-07-22 15:43:33 | DEBUG | Amy Poehler - Yes Please LL.(20910157) was sent to DIRECT
2017-07-22 15:43:33 | INFO | Successfully processed: Yes Please - Amy Poehler
2017-07-22 15:43:33 | DEBUG | Deleted Amy Poehler - Yes Please LL.(20910157), direct from direct
2017-07-22 15:43:33 | ERROR | processExtras: No dest_file supplied
2017-07-22 15:43:33 | DEBUG | Processed direct: Yes Please - Amy Poehler, http://download.libgen.io/get.php?md5=4515217CF5F7C85B8DA12383618EC287&key=BWBNKBGAXWSKNCOJ
2017-07-22 15:43:33 | INFO | Library scan complete
2017-07-22 15:43:33 | DEBUG | Updating bookcounts for 1 author
2017-07-22 15:43:33 | INFO | 2 files processed
2017-07-22 15:43:33 | INFO | 1/1 new/modified eBooks found and added to the database
2017-07-22 15:43:33 | DEBUG | Amy Poehler Yes Please (9780062268372) matched Snatched BookID 20910157, [Amy Poehler][Yes Please]
2017-07-22 15:43:33 | WARNING | Updating book location for Amy Poehler Yes Please (9780062268372) from /books/Amy Poehler/Yes Please (118)/Yes Please - Amy Poehler.epub to /books/Amy Poehler/Yes Please (119)/Yes Please - Amy Poehler.epub
2017-07-22 15:43:33 | DEBUG | Link to preferred type epub: /books/Amy Poehler/Yes Please (119)/Yes Please - Amy Poehler.epub
2017-07-22 15:43:33 | DEBUG | Fuzz match partial [99] [Yes Please (9780062268372)] [Yes Please]
2017-07-22 15:43:33 | DEBUG | Searching 1 book by [Amy Poehler] in database for [Yes Please (9780062268372)]
2017-07-22 15:43:33 | DEBUG | Searching database for [Yes Please (9780062268372)] by [Amy Poehler]
2017-07-22 15:43:33 | DEBUG | Preferred authorname changed from [Poehler, Amy] to [Amy Poehler]
2017-07-22 15:43:33 | DEBUG | Formatted authorname [Poehler, Amy] to [Amy Poehler]
2017-07-22 15:43:33 | DEBUG | book meta [] [en] [Poehler, Amy] [Yes Please (9780062268372)] [epub]
2017-07-22 15:43:33 | DEBUG | [/books/Amy Poehler/] Now scanning subdirectory Yes Please (119)
2017-07-22 15:43:33 | INFO | Scanning eBook directory: /books/Amy Poehler/
2017-07-22 15:43:33 | DEBUG | /opt/calibre/calibredb identifier reports: No write acces to /root/.config/calibre using a temporary dir instead Title : Yes Please Title sort : Yes Please (9780062268372) Author(s) : Amy Poehler [Poehler, Amy] Publisher : HarperCollins Languages : eng Timestamp : 2017-07-22T19:43:27+00:00 Published : 0101-01-01T00:00:00+00:00 Identifiers : goodreads:20910157
2017-07-22 15:43:32 | DEBUG | [u'/opt/calibre/calibredb', 'set_metadata', '--field', u'identifiers:goodreads:20910157', '--with-library', u'/books', '119']
2017-07-22 15:43:32 | DEBUG | /opt/calibre/calibredb title reports: No write acces to /root/.config/calibre using a temporary dir instead Title : Yes Please Title sort : Yes Please (9780062268372) Author(s) : Amy Poehler [Poehler, Amy] Publisher : HarperCollins Languages : eng Timestamp : 2017-07-22T19:43:27+00:00 Published : 0101-01-01T00:00:00+00:00
2017-07-22 15:43:31 | DEBUG | [u'/opt/calibre/calibredb', 'set_metadata', '--field', u'title:Yes Please', '--with-library', u'/books', '119']
2017-07-22 15:43:31 | DEBUG | /opt/calibre/calibredb author reports: No write acces to /root/.config/calibre using a temporary dir instead Title : Yes Please (9780062268372) Title sort : Yes Please (9780062268372) Author(s) : Amy Poehler [Poehler, Amy] Publisher : HarperCollins Languages : eng Timestamp : 2017-07-22T19:43:27+00:00 Published : 0101-01-01T00:00:00+00:00
2017-07-22 15:43:29 | DEBUG | [u'/opt/calibre/calibredb', 'set_metadata', '--field', u'authors:Amy Poehler', '--with-library', u'/books', '119']
2017-07-22 15:43:29 | DEBUG | Calibre ID: 119
2017-07-22 15:43:29 | DEBUG | /opt/calibre/calibredb reports: No write acces to /root/.config/calibre using a temporary dir instead Added book ids: 119
2017-07-22 15:43:26 | DEBUG | [u'/opt/calibre/calibredb', 'add', '-1', u'--with-library=/books', u'/downloads/Amy Poehler - Yes Please LL.(20910157)']
2017-07-22 15:43:26 | DEBUG | Importing Yes Please - Amy Poehler into calibre library
2017-07-22 15:43:26 | DEBUG | Processing eBook 20910157
2017-07-22 15:43:26 | DEBUG | Found match (100%): /downloads/Amy Poehler - Yes Please LL.(20910157) for eBook Amy Poehler - Yes Please LL.(20910157)
2017-07-22 15:43:26 | DEBUG | Found folder (100%) [/downloads/Amy Poehler - Yes Please LL.(20910157)] for eBook Amy Poehler - Yes Please
2017-07-22 15:43:26 | INFO | Looking for eBook Amy Poehler - Yes Please LL.(20910157) in /downloads
2017-07-22 15:43:26 | DEBUG | Amy Poehler - Yes Please LL.(20910157) was sent to DIRECT
2017-07-22 15:43:26 | DEBUG | Found 2 files marked "Snatched"
2017-07-22 15:43:26 | DEBUG | Checking 1 file in /downloads
2017-07-22 15:43:23 | INFO | Log cleared, level set to [2]- Log Directory is [/config/log]

**Comment by Thraxis** [comment]
This should be fixed now in the docker

**Comment by ethanopp** [comment]
I dont seem to be getting the file permission warning anymore, however the main error is still appearing:
"processExtras: No dest_file supplied"

Also got the same error when testing this with calibre shut down per @philborman's comment on: https://github.com/DobyTang/LazyLibrarian/issues/923

Timestamp | Level | Message
-- | -- | --
2017-07-23 09:51:25 | DEBUG | Restart processDir job in 10 minutes
2017-07-23 09:51:25 | DEBUG | Stop processDir job
2017-07-23 09:51:25 | INFO | 1 book/mag processed.
2017-07-23 09:51:25 | DEBUG | Pushbullet devices: None
2017-07-23 09:51:25 | DEBUG | Pushbullet api: o.ZtGcWQvqmUrgOrFkwv6nN16vPTsf6fkO
2017-07-23 09:51:25 | DEBUG | Pushbullet message: eBook Yes Please - Amy Poehler from libgen.io/search.php at 2017-07-23 09:51:25
2017-07-23 09:51:25 | DEBUG | Pushbullet event: Added to Library
2017-07-23 09:51:25 | DEBUG | Pushbullet: Sending notification eBook Yes Please - Amy Poehler from libgen.io/search.php at 2017-07-23 09:51:25
2017-07-23 09:51:25 | INFO | Successfully processed: Yes Please - Amy Poehler
2017-07-23 09:51:25 | DEBUG | Deleted Amy Poehler - Yes Please LL.(20910157), direct from direct
2017-07-23 09:51:25 | ERROR | processExtras: No dest_file supplied
2017-07-23 09:51:25 | DEBUG | Processed direct: Yes Please - Amy Poehler, http://download.libgen.io/get.php?md5=4515217CF5F7C85B8DA12383618EC287&key=BAP5QY2D1R3Q2ZWF
2017-07-23 09:51:25 | INFO | Library scan complete
2017-07-23 09:51:25 | DEBUG | Updating bookcounts for 1 author
2017-07-23 09:51:25 | INFO | 2 files processed
2017-07-23 09:51:25 | INFO | 1/1 new/modified eBooks found and added to the database
2017-07-23 09:51:24 | DEBUG | Amy Poehler Yes Please (9780062268372) matched Snatched BookID 20910157, [Amy Poehler][Yes Please]
2017-07-23 09:51:24 | WARNING | Updating book location for Amy Poehler Yes Please (9780062268372) from /books/Amy Poehler/Yes Please (185)/Yes Please - Amy Poehler.epub to /books/Amy Poehler/Yes Please (186)/Yes Please - Amy Poehler.epub
2017-07-23 09:51:24 | DEBUG | Link to preferred type epub: /books/Amy Poehler/Yes Please (186)/Yes Please - Amy Poehler.epub
2017-07-23 09:51:24 | DEBUG | Fuzz match partial [99] [Yes Please (9780062268372)] [Yes Please]
2017-07-23 09:51:24 | DEBUG | Searching 1 book by [Amy Poehler] in database for [Yes Please (9780062268372)]
2017-07-23 09:51:24 | DEBUG | Searching database for [Yes Please (9780062268372)] by [Amy Poehler]
2017-07-23 09:51:24 | DEBUG | Preferred authorname changed from [Poehler, Amy] to [Amy Poehler]
2017-07-23 09:51:24 | DEBUG | Formatted authorname [Poehler, Amy] to [Amy Poehler]
2017-07-23 09:51:24 | DEBUG | book meta [] [en] [Poehler, Amy] [Yes Please (9780062268372)] [epub]
2017-07-23 09:51:24 | DEBUG | [/books/Amy Poehler/] Now scanning subdirectory Yes Please (186)
2017-07-23 09:51:24 | INFO | Scanning eBook directory: /books/Amy Poehler/
2017-07-23 09:51:24 | DEBUG | /opt/calibre/calibredb identifier reports: Title : Yes Please Title sort : Yes Please (9780062268372) Author(s) : Amy Poehler [Poehler, Amy] Publisher : HarperCollins Languages : eng Timestamp : 2017-07-23T13:51:19+00:00 Published : 0101-01-01T00:00:00+00:00 Identifiers : goodreads:20910157
2017-07-23 09:51:23 | DEBUG | [u'/opt/calibre/calibredb', 'set_metadata', '--field', u'identifiers:goodreads:20910157', '--with-library', u'/books', '186']
2017-07-23 09:51:23 | DEBUG | /opt/calibre/calibredb title reports: Title : Yes Please Title sort : Yes Please (9780062268372) Author(s) : Amy Poehler [Poehler, Amy] Publisher : HarperCollins Languages : eng Timestamp : 2017-07-23T13:51:19+00:00 Published : 0101-01-01T00:00:00+00:00
2017-07-23 09:51:22 | DEBUG | [u'/opt/calibre/calibredb', 'set_metadata', '--field', u'title:Yes Please', '--with-library', u'/books', '186']
2017-07-23 09:51:22 | DEBUG | /opt/calibre/calibredb author reports: Title : Yes Please (9780062268372) Title sort : Yes Please (9780062268372) Author(s) : Amy Poehler [Poehler, Amy] Publisher : HarperCollins Languages : eng Timestamp : 2017-07-23T13:51:19+00:00 Published : 0101-01-01T00:00:00+00:00
2017-07-23 09:51:21 | DEBUG | [u'/opt/calibre/calibredb', 'set_metadata', '--field', u'authors:Amy Poehler', '--with-library', u'/books', '186']
2017-07-23 09:51:21 | DEBUG | Calibre ID: 186
2017-07-23 09:51:21 | DEBUG | /opt/calibre/calibredb reports: Added book ids: 186
2017-07-23 09:51:19 | DEBUG | [u'/opt/calibre/calibredb', 'add', '-1', u'--with-library=/books', u'/downloads/completed/LazyLibrarian/Amy Poehler - Yes Please LL.(20910157)']
2017-07-23 09:51:19 | DEBUG | Importing Yes Please - Amy Poehler into calibre library
2017-07-23 09:51:19 | DEBUG | Processing eBook 20910157
2017-07-23 09:51:19 | DEBUG | Found match (100%): /downloads/completed/LazyLibrarian/Amy Poehler - Yes Please LL.(20910157) for eBook Amy Poehler - Yes Please LL.(20910157)
2017-07-23 09:51:19 | DEBUG | Found folder (100%) [/downloads/completed/LazyLibrarian/Amy Poehler - Yes Please LL.(20910157)] for eBook Amy Poehler - Yes Please
2017-07-23 09:51:19 | INFO | Looking for eBook Amy Poehler - Yes Please LL.(20910157) in /downloads/completed/LazyLibrarian
2017-07-23 09:51:19 | DEBUG | Amy Poehler - Yes Please LL.(20910157) was sent to DIRECT
2017-07-23 09:51:19 | DEBUG | Closest match (29%): /downloads/completed/LazyLibrarian/Amy Poehler - Yes Please LL.(20910157)
2017-07-23 09:51:19 | DEBUG | Snatched torznab Tarryn Fisher - Marrow LL.(25379213) is not in download directory
2017-07-23 09:51:19 | INFO | Looking for eBook Tarryn Fisher - Marrow LL.(25379213) in /downloads/completed/LazyLibrarian
2017-07-23 09:51:19 | DEBUG | Requesting URL via POST method: http://10.0.3.1:9091/transmission/rpc
2017-07-23 09:51:19 | DEBUG | Requesting URL via GET method: http://10.0.3.1:9091/transmission/rpc
2017-07-23 09:51:14 | DEBUG | Requesting URL via POST method: http://10.0.3.1:9091/transmission/rpc
2017-07-23 09:51:14 | DEBUG | Requesting URL via GET method: http://10.0.3.1:9091/transmission/rpc
2017-07-23 09:51:09 | DEBUG | Requesting URL via POST method: http://10.0.3.1:9091/transmission/rpc
2017-07-23 09:51:09 | DEBUG | Requesting URL via GET method: http://10.0.3.1:9091/transmission/rpc
2017-07-23 09:51:09 | DEBUG | Tarryn Fisher - Marrow LL.(25379213) was sent to TRANSMISSION
2017-07-23 09:51:09 | DEBUG | Closest match (18%): /downloads/completed/LazyLibrarian/Amy Poehler - Yes Please LL.(20910157)
2017-07-23 09:51:09 | DEBUG | Snatched torznab Megan Miranda - All the Missing Girls LL.(27276324) is not in download directory
2017-07-23 09:51:09 | INFO | Looking for eBook Megan Miranda - All the Missing Girls LL.(27276324) in /downloads/completed/LazyLibrarian
2017-07-23 09:51:09 | DEBUG | getTorrentFolder: No response from transmission
2017-07-23 09:51:09 | DEBUG | Requesting URL via POST method: http://10.0.3.1:9091/transmission/rpc
2017-07-23 09:51:09 | DEBUG | Requesting URL via GET method: http://10.0.3.1:9091/transmission/rpc
2017-07-23 09:51:09 | DEBUG | Megan Miranda - All the Missing Girls LL.(27276324) was sent to TRANSMISSION
2017-07-23 09:51:09 | DEBUG | Closest match (42%): /downloads/completed/LazyLibrarian/Amy Poehler - Yes Please LL.(20910157)
2017-07-23 09:51:09 | DEBUG | Snatched torznab Paulo Coelho - The Alchemist LL.(865) is not in download directory
2017-07-23 09:51:09 | INFO | Looking for eBook Paulo Coelho - The Alchemist LL.(865) in /downloads/completed/LazyLibrarian
2017-07-23 09:51:09 | DEBUG | getTorrentFolder: No response from transmission
2017-07-23 09:51:09 | DEBUG | Requesting URL via POST method: http://10.0.3.1:9091/transmission/rpc
2017-07-23 09:51:09 | DEBUG | Requesting URL via GET method: http://10.0.3.1:9091/transmission/rpc
2017-07-23 09:51:09 | DEBUG | Paulo Coelho - The Alchemist LL.(865) was sent to TRANSMISSION
2017-07-23 09:51:09 | DEBUG | Closest match (29%): /downloads/completed/LazyLibrarian/Amy Poehler - Yes Please LL.(20910157)
2017-07-23 09:51:09 | DEBUG | Snatched magnet Everything All at Once by Bill Nye ePUB MOBI eBOOK-ZAK is not in download directory
2017-07-23 09:51:09 | INFO | Looking for eBook Everything All at Once by Bill Nye ePUB MOBI eBOOK-ZAK in /downloads/completed/LazyLibrarian
2017-07-23 09:51:09 | DEBUG | getTorrentFolder: No response from transmission
2017-07-23 09:51:09 | DEBUG | Requesting URL via POST method: http://10.0.3.1:9091/transmission/rpc
2017-07-23 09:51:09 | DEBUG | Requesting URL via GET method: http://10.0.3.1:9091/transmission/rpc
2017-07-23 09:51:09 | DEBUG | Everything All at Once by Bill Nye ePUB MOBI eBOOK-ZAK was sent to TRANSMISSION
2017-07-23 09:51:09 | DEBUG | Found 5 files marked "Snatched"
2017-07-23 09:51:09 | DEBUG | Checking 1 file in /downloads/completed/LazyLibrarian
2017-07-23 09:51:06 | INFO | Log cleared, level set to [2]- Log Directory is [/config/log]

**Comment by ethanopp** [comment]
Updated per @philborman in https://github.com/DobyTang/LazyLibrarian/issues/923
